### ISSUE TITLE
Have a Smooth Transition Between Flying and Walking

### ISSUE THREAD

**Issue by ChaoticEvan** [Capstone-Shiny-Game/Shiny#25]
Smoothly transition between flying/walking states of movement

**Comment by j-a-m-e-s** [comment]
Suggestions for implementation details.

Upon keypress for switching to walking quickly decrease bird speed to 0. Then drop to the ground after

For transitioning to flying (probably using the same key as landing), have the crow launch forward and up and start flying at that velocity.

free camera rotation to user, this will be  done with swipes with the right hand on mobile
realign camera to behind the crow when they take off.
